from django.urls import path
from . import views

urlpatterns = [
    path('incoming/', views.income_list, name='income_list'),
    path('', views.expense_list, name='expense_list'),
    path('expenses/add/', views.add_expense, name='add_expense'),
    path('expenses/filter/', views.filter_expenses, name='filter_expenses'),
    path('expenses/<int:expense_id>/edit/', views.edit_expense, name='edit_expense'),
    path('expenses/<int:expense_id>/delete/', views.delete_expense, name='delete_expense'),
    path('categories/', views.category_list, name='category_list'),
    path('categories/<int:category_id>/delete/', views.delete_category, name='delete_category'),
    path('expenses/export/csv/', views.export_expenses_csv, name='export_expenses'),
    path('expenses/import/csv/', views.import_expenses_csv, name='import_expenses'),
    path('income/', views.income_list, name='income_list'),
    path('income/add/', views.add_income, name='add_income'),
    path('income/<int:income_id>/edit/', views.edit_income, name='edit_income'),
    path('income/<int:income_id>/delete/', views.delete_income, name='delete_income'),
    path('income_categories/', views.income_category_list, name='income_category_list'),
    path('add_income_category/', views.add_income_category, name='add_income_category'),
    path('delete_income_category/<int:category_id>/', views.delete_income_category, name='delete_income_category'),
    path('debts/', views.debts_list, name='debts_list'),
    path('add_debt/', views.add_debts, name='add_debts'),
    path('debts/<int:debts_id>/delete/', views.delete_debts, name='delete_debts'),
    path('income_expense_report/', views.income_expense_report, name='income_expense_report'),
    path('budget/category/<int:category_id>/expenses/<int:month>/<int:year>/', views.category_expense_report,
         name='category_expense_report'),
    path('select_category_report/', views.select_category_report, name='select_category_report'),
    path('create_family/', views.create_family, name='create_family'),
    path('join_family/', views.join_family, name='join_family'),
    path('leave_family/', views.leave_family, name='leave_family'),
    path('dashboard/', views.dashboard, name='dashboard'),
    path('add_category/', views.add_category, name='add_category'),
    path('subcategory_list/', views.subcategory_list, name='subcategory_list'),
    path('add_subcategory/', views.add_subcategory, name='add_subcategory'),
    path('subcategory/<int:subcategory_id>/delete/', views.delete_subcategory, name='delete_subcategory'),
    path('currency_converter/', views.currency_converter, name='currency_converter'),
    path('currency/', views.currency_rates, name='currency_rates'),

]
